-- ACTIONS
INSERT INTO ACTIONS(ACTION_NAME) VALUES('LOGIN');
INSERT INTO ACTIONS(ACTION_NAME) VALUES('VIEW');
INSERT INTO ACTIONS(ACTION_NAME) VALUES('EDIT');
INSERT INTO ACTIONS(ACTION_NAME) VALUES('CREATE');
INSERT INTO ACTIONS(ACTION_NAME) VALUES('GRANT_ADMIN');

-- RESOURCES
INSERT INTO RESOURCES(RESOURCE_NAME) VALUES('ACCOUNT');
INSERT INTO RESOURCES(RESOURCE_NAME) VALUES('ADMIN_PAGES');
INSERT INTO RESOURCES(RESOURCE_NAME) VALUES('ROLE');

-- ROLES
INSERT INTO ROLES(ROLE_NAME) VALUES('USER');
INSERT INTO ROLES(ROLE_NAME) VALUES('ADMIN');


-- USER ROLE
-- ACCOUNT
INSERT INTO ROLE_PERMISSIONS(ROLE_SID,RESOURCE_SID,ACTION_SID) VALUES((select ROLE_SID from ROLES where ROLE_NAME='USER'), (select RESOURCE_SID from RESOURCES where RESOURCE_NAME='ACCOUNT'), (select ACTION_SID from ACTIONS where ACTION_NAME='LOGIN'));
INSERT INTO ROLE_PERMISSIONS(ROLE_SID,RESOURCE_SID,ACTION_SID) VALUES((select ROLE_SID from ROLES where ROLE_NAME='USER'), (select RESOURCE_SID from RESOURCES where RESOURCE_NAME='ACCOUNT'), (select ACTION_SID from ACTIONS where ACTION_NAME='VIEW'));
INSERT INTO ROLE_PERMISSIONS(ROLE_SID,RESOURCE_SID,ACTION_SID) VALUES((select ROLE_SID from ROLES where ROLE_NAME='USER'), (select RESOURCE_SID from RESOURCES where RESOURCE_NAME='ACCOUNT'), (select ACTION_SID from ACTIONS where ACTION_NAME='EDIT'));

-- ADMIN ROLE
-- ACCOUNT
INSERT INTO ROLE_PERMISSIONS(ROLE_SID,RESOURCE_SID,ACTION_SID) VALUES((select ROLE_SID from ROLES where ROLE_NAME='ADMIN'), (select RESOURCE_SID from RESOURCES where RESOURCE_NAME='ACCOUNT'), (select ACTION_SID from ACTIONS where ACTION_NAME='LOGIN'));
INSERT INTO ROLE_PERMISSIONS(ROLE_SID,RESOURCE_SID,ACTION_SID) VALUES((select ROLE_SID from ROLES where ROLE_NAME='ADMIN'), (select RESOURCE_SID from RESOURCES where RESOURCE_NAME='ACCOUNT'), (select ACTION_SID from ACTIONS where ACTION_NAME='VIEW'));
INSERT INTO ROLE_PERMISSIONS(ROLE_SID,RESOURCE_SID,ACTION_SID) VALUES((select ROLE_SID from ROLES where ROLE_NAME='ADMIN'), (select RESOURCE_SID from RESOURCES where RESOURCE_NAME='ACCOUNT'), (select ACTION_SID from ACTIONS where ACTION_NAME='EDIT'));
-- ADMIN_PAGES
INSERT INTO ROLE_PERMISSIONS(ROLE_SID,RESOURCE_SID,ACTION_SID) VALUES((select ROLE_SID from ROLES where ROLE_NAME='ADMIN'), (select RESOURCE_SID from RESOURCES where RESOURCE_NAME='ADMIN_PAGES'), (select ACTION_SID from ACTIONS where ACTION_NAME='VIEW'));
-- ROLE
INSERT INTO ROLE_PERMISSIONS(ROLE_SID,RESOURCE_SID,ACTION_SID) VALUES((select ROLE_SID from ROLES where ROLE_NAME='ADMIN'), (select RESOURCE_SID from RESOURCES where RESOURCE_NAME='ROLE'), (select ACTION_SID from ACTIONS where ACTION_NAME='VIEW'));
INSERT INTO ROLE_PERMISSIONS(ROLE_SID,RESOURCE_SID,ACTION_SID) VALUES((select ROLE_SID from ROLES where ROLE_NAME='ADMIN'), (select RESOURCE_SID from RESOURCES where RESOURCE_NAME='ROLE'), (select ACTION_SID from ACTIONS where ACTION_NAME='CREATE'));
